name: coverage_and_test

on:
  pull_request_target:
    types: [opened, synchronize, edited]
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:  
          python-version: 3.9  
          
      - name: Install dependencies  
        run: |  
          pip install -r scripts/requirements.txt
          
      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      
      - name: initial moon test
        run: moon test --enable-coverage

      - name: initial coverage report
        run: |
          moon coverage report -f summary > coverage_summary.txt
          
          cat coverage_summary.txt >> "$GITHUB_STEP_SUMMARY"

          moon coverage report -f coveralls

      - name: coverage improvement
        run: python scripts/testagent.py --api_key ${{ secrets.api_key }}
      
      - name: Get code changes
        id: get_code_changes
        run: |
            git diff > changes.txt   
            test_code=$(cat changes.txt)   
            echo "test_code=$test_code" >> $GITHUB_ENV  

      - name: Push comments
        uses: peter-evans/create-or-update-comment@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            commit-sha: ${{ github.event.pull_request.head.sha }}
            body: |
              Here are the test code changes:  
              ```  
              ${{ env.test_code }}  
              ```
            reaction-type: rocket
